/**
 * Renders every keybinding this configuration sets as one scannable page.
 *
 * The binds come from `vim.keymaps`, and the group names come from
 * `vim.binds.whichKey.register` — the same labels which-key shows in the editor,
 * so the page and the popup can never disagree.
 */
import {escapeMdxDescription} from './value';

export interface Keymap {
  key: string;
  /** nvf accepts either a bare mode or a list of them. */
  mode: string | string[];
  desc?: string | null;
  action?: string;
}

/** A which-key prefix registry: `"<leader>f"` -> `"Find"`. */
export type WhichKeyRegister = Record<string, string>;

export interface KeymapGroup {
  label: string;
  entries: Keymap[];
}

const LEADER = '<leader>';
const OTHER_LEADER = 'Other leader keys';
const WITHOUT_LEADER = 'Without leader';

export function normalizeModes(mode: string | string[]): string[] {
  return Array.isArray(mode) ? mode : [mode];
}

/**
 * Shows the mode only when it is worth showing. Nearly every bind is
 * normal-mode-only, so printing "n" 100 times is noise that hides the handful
 * of binds that genuinely differ.
 */
export function formatModes(mode: string | string[]): string {
  const modes = normalizeModes(mode);
  if (modes.length === 1 && modes[0] === 'n') return '';
  return modes.join(', ');
}

/**
 * Finds the registered which-key prefix a bind belongs under: the longest
 * registered prefix that is a strict prefix of the key.
 */
export function groupLabelFor(key: string, register: WhichKeyRegister): string {
  const prefixes = Object.keys(register)
    .filter((prefix) => key.startsWith(prefix) && key !== prefix)
    .sort((a, b) => b.length - a.length);

  // which-key labels group prefixes with a leading `+` by convention; it is
  // popup shorthand and reads as noise in a heading.
  if (prefixes.length > 0) return register[prefixes[0]].replace(/^\+/, '');
  return key.startsWith(LEADER) ? OTHER_LEADER : WITHOUT_LEADER;
}

/**
 * Buckets binds by which-key group. Named groups come first in alphabetical
 * order, then the two catch-alls, so the page always reads the same way.
 */
export function groupKeymaps(
  keymaps: Keymap[],
  register: WhichKeyRegister,
): KeymapGroup[] {
  const buckets = new Map<string, Keymap[]>();

  for (const keymap of keymaps) {
    const label = groupLabelFor(keymap.key, register);
    const bucket = buckets.get(label);
    if (bucket) bucket.push(keymap);
    else buckets.set(label, [keymap]);
  }

  const catchAlls = [OTHER_LEADER, WITHOUT_LEADER];
  const named = [...buckets.keys()]
    .filter((label) => !catchAlls.includes(label))
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));

  return [...named, ...catchAlls]
    .filter((label) => buckets.has(label))
    .map((label) => ({
      label,
      entries: [...buckets.get(label)!].sort((a, b) =>
        a.key < b.key ? -1 : a.key > b.key ? 1 : 0,
      ),
    }));
}

/** Escapes the one character that would break out of a markdown table cell. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function renderGroup(group: KeymapGroup): string {
  const showMode = group.entries.some((entry) => formatModes(entry.mode) !== '');

  const header = showMode
    ? ['| Key | Action | Mode |', '| --- | --- | --- |']
    : ['| Key | Action |', '| --- | --- |'];

  const rows = group.entries.map((entry) => {
    const key = `\`${cell(entry.key)}\``;
    const desc = escapeMdxDescription(cell(entry.desc ?? ''));
    // Once the column exists every row fills it — a blank cell reads as missing
    // data rather than as "normal mode".
    const modes = cell(normalizeModes(entry.mode).join(', '));
    return showMode ? `| ${key} | ${desc} | ${modes} |` : `| ${key} | ${desc} |`;
  });

  return [`## ${group.label}`, '', ...header, ...rows, ''].join('\n');
}

export function renderKeybindingsPage(
  keymaps: Keymap[],
  register: WhichKeyRegister,
): string {
  const groups = groupKeymaps(keymaps, register);

  const header = [
    '---',
    'title: Keybindings',
    'sidebar_label: Keybindings',
    'sidebar_position: 1',
    'description: Every keybinding this configuration sets',
    '---',
    '',
    '# Keybindings',
    '',
    '{/* This page is generated by docs/scripts/render-options.ts. Do not edit it by hand. */}',
    '',
    `The leader key is \`<Space>\`. This page lists all ${keymaps.length} binds this ` +
      'configuration sets, generated from the same Nix evaluation that builds the editor. ' +
      'Groups match the which-key popup, and the mode column appears only where a bind is ' +
      'not normal-mode-only.',
    '',
    '',
  ].join('\n');

  return header + groups.map(renderGroup).join('\n');
}
