import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Option Reference',
      link: {
        type: 'generated-index',
        description:
          'Every nvf option this configuration sets, generated from a live Nix evaluation.',
      },
      items: [{type: 'autogenerated', dirName: 'reference/options'}],
    },
  ],
};

export default sidebars;
